# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  twitter: guidotorresmx
  facebook: guidotorresmx
  linkedin: guidotorresmx
  instagram: guidotorresmx
  github: guidotorresmx
  mail: marco@guidotorres.mx
  phone: 16479066194
  telegram: guidotorresmx

user:
  name: Marco Guido
  avatar: /images/avatar.jpg
  location: Toronto, ON
  description: Programming, electronics and stuff
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: guidotorresmx # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/favicon.png

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png
